//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutodetailsEntities : DbContext
    {
        public AutodetailsEntities()
            : base("name=AutodetailsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        private static AutodetailsEntities _context;
        public static AutodetailsEntities GetContext()
        {
            if (_context == null)
                _context = new AutodetailsEntities();
            return _context;
        }

        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<NameParts> NameParts { get; set; }
        public virtual DbSet<Requests> Requests { get; set; }
        public virtual DbSet<RequestStatus> RequestStatus { get; set; }
        public virtual DbSet<Role_> Role_ { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
    }
}
